# Generated by Django 5.0.4 on 2024-05-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_userdefinecategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDefineCategory',
        ),
    ]
