# Generated by Django 5.0.4 on 2024-05-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_userdefinecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
