# Generated by Django 5.0.4 on 2024-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_icon_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
