# Generated by Django 5.0.4 on 2024-05-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('date_opened', models.DateField(auto_now=True)),
                ('date_closed', models.DateField(null=True)),
                ('account_status', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bankaccount.branch')),
            ],
        ),
    ]
