# Generated by Django 5.0.4 on 2024-05-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='bankaccount',
            table_comment='A table for all the bank accounts',
        ),
        migrations.AlterModelTableComment(
            name='branch',
            table_comment='A table for all the branchs',
        ),
        migrations.AlterModelTable(
            name='bankaccount',
            table='bankaccount',
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
