# Generated by Django 5.0.4 on 2024-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_income_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
