# Generated by Django 5.0.4 on 2024-05-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.IntegerField()),
                ('week', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('amount', models.FloatField()),
                ('type', models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense'), ('TRANSFER', 'transfer')], max_length=40)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
