# Generated by Django 5.0.4 on 2024-05-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '__first__'),
        ('wallet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_amount', models.FloatField(default=0.0)),
                ('current_expenditure', models.FloatField(default=0.0)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
