# Generated by Django 5.0.4 on 2024-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
