# Generated by Django 5.0.4 on 2024-05-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='transaction',
            table_comment='A table for all the transactions',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
