# Generated by Django 5.0.4 on 2024-05-05 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_expense_description'),
        ('income', '0003_alter_income_description'),
        ('transaction', '0002_alter_transaction_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.expense'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='income.income'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense')], max_length=40),
        ),
    ]
