# Generated by Django 5.0.4 on 2024-05-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
