# Generated by Django 5.0.4 on 2024-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_transaction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense'), ('TRANSFER', 'transfer')], max_length=40),
        ),
    ]
