# Generated by Django 5.0.4 on 2024-05-03 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recurring', models.BooleanField()),
                ('repeat_occurrence', models.IntegerField()),
                ('repeat_schedule', models.CharField(max_length=25)),
                ('payment_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=25)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.expense')),
                ('income', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income.income')),
            ],
        ),
    ]
