# Generated by Django 5.0.4 on 2024-05-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedpayments', '0003_alter_plannedpayment_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpayment',
            name='repeat_occurrence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedpayment',
            name='repeat_schedule',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'monthly'), ('WEEKLY', 'weekly'), ('DAILY', 'daily')], max_length=25, null=True),
        ),
    ]
