# Generated by Django 5.0.4 on 2024-05-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plannedpayments', '0005_plannedpayment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedpayment',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='plannedpayment',
            name='income',
        ),
    ]
