# Generated by Django 5.0.4 on 2024-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedpayments', '0006_remove_plannedpayment_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpayment',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
