# Generated by Django 5.0.4 on 2024-05-15 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_delete_userdefinecategory'),
        ('plannedpayments', '0007_plannedpayment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AddField(
            model_name='plannedpayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
