# Generated by Django 5.0.4 on 2024-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedpayments', '0008_plannedpayment_amount_plannedpayment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
    ]
