# Generated by Django 5.0.4 on 2024-05-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannedpayments', '0009_alter_plannedpayment_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedpayment',
            name='repeat_schedule',
            field=models.CharField(blank=True, choices=[('MONTH', 'month'), ('WEEK', 'week'), ('DAY', 'day'), ('YEAR', 'year')], max_length=25, null=True),
        ),
    ]
