# Generated by Django 5.0.4 on 2024-05-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='wallet',
            table_comment='A table for all the wallets',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
    ]
