# Generated by Django 5.0.4 on 2024-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
